apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-docusign-ingester
spec:
  replicas: {{ .Values.replicas }}
  template:
    spec:
      containers:
        - name: docusign-ingester
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080