apiVersion: apps/v1
kind: Deployment
metadata:
  name: docusign-ingester
  namespace: docusign
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docusign-ingester
  template:
    metadata:
      labels:
        app: docusign-ingester
    spec:
      containers:
      - name: docusign-ingester
        image: 868232756949.dkr.ecr.eu-west-2.amazonaws.com/docusign-ingester:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
