# fly.toml app configuration file generated for app-divine-moon-1530 on 2024-10-29T12:24:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-divine-moon-1530'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
